# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2(self):
    self.driver.get("http://192.168.20.11/sws/index.sws")
    self.driver.set_window_size(1552, 832)
    self.driver.switch_to.frame(1)
    self.vars["toner_negro"] = self.driver.find_element(By.XPATH, "//tr[@id=\'1\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]").text
    self.vars["toner_cian"] = self.driver.find_element(By.XPATH, "//tr[@id=\'2\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]").text
    self.vars["toner_magenta"] = self.driver.find_element(By.XPATH, "//tr[@id=\'3\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]").text
    self.vars["toner_amarillo"] = self.driver.find_element(By.XPATH, "//tr[@id=\'4\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]").text
    self.vars["ui_negro"] = self.driver.find_element(By.XPATH, "(//tr[@id=\'1\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2])[2]").text
    self.vars["ui_cian"] = self.driver.find_element(By.XPATH, "(//tr[@id=\'2\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2])[2]").text
    self.vars["ui_magenta"] = self.driver.find_element(By.XPATH, "(//tr[@id=\'3\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2])[2]").text
    self.vars["ui_amarillo"] = self.driver.find_element(By.XPATH, "(//tr[@id=\'4\']/td[2]/table/tbody/tr/td/table/tbody/tr/td[2])[2]").text
    print("Toner Negro Restante: {}, UI Negro Restante:  ${ui_negro}".format(self.vars["toner_negro"]))
    print("Toner Cian Restante: {}, UI Cian Restante:  ${ui_cian}".format(self.vars["toner_cian"]))
    print("Toner Magenta Restante: {}, UI Magenta Restante:  ${ui_magenta}".format(self.vars["toner_magenta"]))
    print("Toner Amarillo Restante: {}, UI Amarillo Restante:  ${ui_amarillo}".format(self.vars["toner_amarillo"]))
  
